#!/bin/sh

git stash

cargo clippy --tests -- -D warnings && \
	cargo fmt -- --check && \
	cargo nextest run && \
	docker build -t zero2prod:push . && \
	docker image rm zero2prod:push && \
	ERR=$?

git stash pop
exit $ERR
