# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Lint Cargo

on:
  workflow_call:
    inputs:
      rust-version:
        description: Rust version
        required: true
        type: string

jobs:
  lint-cargo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust setup
        uses: ./.github/actions/setup-rust
        with:
          rust-version: ${{ inputs.rust-version }}

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Cargo clippy
        run: cargo clippy  -- -D warnings
