# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Test Cargo

on:
  workflow_call:
    inputs:
      rust-version:
        description: Rust version
        required: true
        type: string

jobs:
  test-cargo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust setup
        uses: ./.github/actions/setup-rust
        with:
          rust-version: ${{ inputs.rust-version }}

      - uses: taiki-e/install-action@nextest

      - name: Cargo test
        run: RUST_TEST=1 cargo nextest run
